### ISSUE TITLE
Dat-cli crashes syncing

### ISSUE THREAD

**Issue by icarito** [datproject/projects#26]
### Who are the users?
This is directory updated few times per day, few files at a time.
The crash comes when syncing from a different machine running Ubuntu 16.04 and Nodejs v4.2.6
### How would the user interact with it?
```
icarito@sunjammer:~/public_html/Workspace$ dat sync .                                                                                         │···············
(node) Buffer.set is deprecated. Use array indexes instead.                                                                                   │···············
dat v13.8.1                                                                                                                                   │···············
Downloading dat: 136 files (2.4 MB)                                                                                                           │···············
                                                                                                                                              │···············
1 connection | Download 0 B/s Upload 0 B/s                                                                                                    │···············
                   7 files (2.4 MB)                                                                                                           │···············
dat synced, waiting8 files (2.4 MB)                                                                                                           │···············
[=======================0 B/s Upload 0 B/s                                                                                                    │···············
0 connections | Download 595 B/s Upload 0 B/s                                                                                                 │···············
dat synced, waiting for updates.                                                                                                              │···············
Downloading updates...                                                                                                                        │···············
                                               1.22%                                                                                          │···············
                                                                                                                                              │···············
                                                                                                                                              │···············
                                                                                                                                              │···············
/usr/local/lib/node_modules/dat/src/lib/download.js:33                                                                                        │···············
      debug('archive sync', state.stats.get())                                                                                                │···············
      ^                                                                                                                                       │···············
                                                                                                                                              │···············
RangeError: Maximum call stack size exceeded                                                                                                  │···············
    at Hyperdrive.<anonymous> (/usr/local/lib/node_modules/dat/src/lib/download.js:33:7)                                                      │···············
    at emitNone (events.js:67:13)                                                                                                             │···············
    at Hyperdrive.emit (events.js:166:7)                                                                                                      │···············
    at /usr/local/lib/node_modules/dat/node_modules/hyperdrive/index.js:141:14                                                                │···············
    at kick (/usr/local/lib/node_modules/dat/node_modules/hyperdrive/index.js:236:5)                                                          │···············
    at Object.callback (/usr/local/lib/node_modules/dat/node_modules/hyperdrive/index.js:223:7)                                               │···············
    at Peer._downloadRange (/usr/local/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:368:13)                                   │···············
    at Peer.update (/usr/local/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:299:12)                                           │···············
    at Peer.update (/usr/local/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:300:51)                                           │···············
    at Peer.update (/usr/local/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:300:51)                                           │···············
```
### Why is the project important to the ecosystem?
Dat-cli shouldn't crash ;-)

**Comment by icarito** [comment]
fwif dat is here: https://github.com/somosazucar/Jappy/tree/master/workspace

**Comment by icarito** [comment]
wrong repo, sorry
